// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vyjhpuymonmpxubacrem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5amhwdXltb25tcHh1YmFjcmVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ3NjUzMjQsImV4cCI6MjA1MDM0MTMyNH0.E5Rrmh-sKsICPAwTu9CSB6cfsC33yEWcUouMpEw3_-I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);